name: flutter_widgetbook_example
description: A simple Flutter project implementing Widgetbook
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  widgetbook: ^2.4.1
  widgetbook_annotation: ^2.1.0
  build_runner: ^2.3.3
  widgetbook_generator: ^2.4.1

flutter:
  uses-material-design: true